### ISSUE TITLE
`Invalid request` when posting annotations

### ISSUE THREAD

**Issue by ZedThree** [ZedThree/clang-tidy-review#139]
```
Traceback (most recent call last):
  File "/usr/local/bin/review", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/clang_tidy_review/review.py", line 174, in main
    post_annotations(pull_request, review)
  File "/usr/local/lib/python3.12/dist-packages/clang_tidy_review/__init__.py", line 1199, in post_annotations
    pull_request.post_annotations(body)
  File "/usr/local/lib/python3.12/dist-packages/clang_tidy_review/__init__.py", line 353, in post_annotations
    self.repo._requester.requestJsonAndCheck(
  File "/usr/local/lib/python3.12/dist-packages/github/Requester.py", line 550, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/github/Requester.py", line 611, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 422 {"message": "Invalid request.\n\nFor 'links/0/schema', nil is not an object.", "documentation_url": "https://docs.github.com/rest/checks/runs#create-a-check-run", "status": "422"}
```

**Comment by ZedThree** [comment]
I think recent fixes have resolved this
